ALTER TABLE workflows ADD COLUMN IF NOT EXISTS ui_schema JSONB DEFAULT '{}'::jsonb;
ALTER TABLE workflow_nodes ADD COLUMN IF NOT EXISTS position_x DOUBLE PRECISION DEFAULT 0;
ALTER TABLE workflow_nodes ADD COLUMN IF NOT EXISTS position_y DOUBLE PRECISION DEFAULT 0;
